version: 2.1
jobs:
  build:
    docker:
      - image: clojure:tools-deps-bullseye-slim
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
            ls -al