version: 2.1
jobs:
  build:
    docker:
      - image: clojure:slim-bullseye
    steps:
      - checkout
      - run:
          name: Run Specs
          command: |
            clojure -M:test:spec -f junit-xml-reporter > spec_results.xml
      - run:
          name: Review Spec Results
          command: |
            cat ./spec_results.xml
      - store_test_results:
          path: ./spec_results.xml