version: 2.1
jobs:
  build:
    docker:
      - image: clojure:tools-deps
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            clj -M:test:spec -f junit-xml-reporter