version: 2.1
jobs:
  build:
    docker:
      - image: clojure:tools-deps
    steps:
      - checkout
      - run:
          name: Run specs
          command: |
            clojure -M:test:spec -f junit-xml-reporter > spec_results.xml
      - store_test_results:
          path: ./spec_results.xml